FROM golang:1.15-alpine as dev

WORKDIR /work

FROM golang:1.15-alpine as build

WORKDIR /videos
COPY ./videos/* /videos/
RUN go build -o videos

FROM alpine:3.18.3 as runtime 
COPY --from=build /videos/videos /
COPY ./videos/videos.json /
CMD ./videos